name: Clean Workflows

on:
  workflow_dispatch:

  schedule:
    - cron: '15 9 */7 * *'
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
       - name: Delete workflow runs
         uses: dmvict/clean-workflow-runs@v1.0.0
         with:
          token: ${{ secrets.ACTION_TOKEN }}
          repo: user/repo
#          workflow_id: 
          branch: main
          run_conclusions: |
           failure
           timed_out
          save_period: 7
          save_min_runs_number: 1
          dry: true
