name: ROS CNIP list

on: 
  workflow_dispatch:
  #push: 
  #   branches:
  #     - master
  watch:
    types: started
  schedule:
    - cron: 1 1 * * *

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Combine
      run: |
        ipipnet="$( curl -kLfsm 5 https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt )"
        clang="$( curl -kLfsm 5 https://ispip.clang.cn/all_cn_cidr.txt )"
        iplist="$ipipnet\n$clang"
        echo -e "${iplist}" | sort | uniq | sed -e 's/^/add address=/g' -e 's/$/ list=CNIP/g' > /tmp/cnip.rsc
        cp cnip.rsc.defconfig cnip.rsc && cat /tmp/cnip.rsc >> cnip.rsc
        echo -e "${iplist}" | sort | uniq > china_ip_list.txt

    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
